package com.qx.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated 2015-9-8 9:22:49 by Hibernate Tools 3.4.0.CR1

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private Integer activityId;
	private String activityName;
	private Integer activityType;
	private String activityImg;
	private Activitytype activityTypeO;
	private Set goodsinfos = new HashSet(0);

	private Date activityStart;
	private Date activityEnd;
	private Integer activityStatus;

	public Date getActivityStart() {
		return activityStart;
	}

	public void setActivityStart(Date activityStart) {
		this.activityStart = activityStart;
	}

	public Date getActivityEnd() {
		return activityEnd;
	}

	public void setActivityEnd(Date activityEnd) {
		this.activityEnd = activityEnd;
	}

	public Integer getActivityStatus() {
		return activityStatus;
	}

	public void setActivityStatus(Integer activityStatus) {
		this.activityStatus = activityStatus;
	}

	public Activitytype getActivityTypeO() {
		return activityTypeO;
	}

	public Set getGoodsinfos() {
		return goodsinfos;
	}

	public void setGoodsinfos(Set goodsinfos) {
		this.goodsinfos = goodsinfos;
	}

	public void setActivityTypeO(Activitytype activityTypeO) {
		this.activityTypeO = activityTypeO;
	}

	public Activity() {
	}

	public Activity(String activityName, Integer activityType,
			String activityImg) {
		this.activityName = activityName;
		this.activityType = activityType;
		this.activityImg = activityImg;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public Integer getActivityType() {
		return this.activityType;
	}

	public void setActivityType(Integer activityType) {
		this.activityType = activityType;
	}

	public String getActivityImg() {
		return this.activityImg;
	}

	public void setActivityImg(String activityImg) {
		this.activityImg = activityImg;
	}

	@Override
	public String toString() {
		return "Activity [activityId=" + activityId + ", activityName="
				+ activityName + ", activityType=" + activityType
				+ ", activityImg=" + activityImg + ", activityStart="
				+ activityStart + ", activityEnd=" + activityEnd
				+ ", activityStatus=" + activityStatus + "]";
	}

}
