package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

/**
 * Addressinfo generated by hbm2java
 */
public class Addressinfo implements java.io.Serializable {

	private Integer addressId;
	private String userId;
	private String addressName;

	public Addressinfo() {
	}

	public Addressinfo(String userId, String addressName) {
		this.userId = userId;
		this.addressName = addressName;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getAddressName() {
		return this.addressName;
	}

	public void setAddressName(String addressName) {
		this.addressName = addressName;
	}

}
