package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Admininfo generated by hbm2java
 */
public class Admininfo implements java.io.Serializable {

	private Integer adminId;
	private String password;
	private Date registerTime;
	private String userName;

	public Admininfo() {
	}

	public Admininfo(String password, Date registerTime, String userName) {
		this.password = password;
		this.registerTime = registerTime;
		this.userName = userName;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
