package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Cartinfo generated by hbm2java
 */
public class Cartinfo implements java.io.Serializable {

	private Integer cartId;
	private Goodsinfo goodsinfo;
	private Userinfo userinfo;
	private Integer orderNum;
	private BigDecimal goodsPrice;
	private BigDecimal totalPrice;
	private Integer addressId;

	public Cartinfo() {
	}

	public Cartinfo(Goodsinfo goodsinfo, Userinfo userinfo) {
		this.goodsinfo = goodsinfo;
		this.userinfo = userinfo;
	}

	public Cartinfo(Goodsinfo goodsinfo, Userinfo userinfo, Integer orderNum,
			BigDecimal goodsPrice, BigDecimal totalPrice, Integer addressId) {
		this.goodsinfo = goodsinfo;
		this.userinfo = userinfo;
		this.orderNum = orderNum;
		this.goodsPrice = goodsPrice;
		this.totalPrice = totalPrice;
		this.addressId = addressId;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public Goodsinfo getGoodsinfo() {
		return this.goodsinfo;
	}

	public void setGoodsinfo(Goodsinfo goodsinfo) {
		this.goodsinfo = goodsinfo;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public BigDecimal getGoodsPrice() {
		return this.goodsPrice;
	}

	public void setGoodsPrice(BigDecimal goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

}
