package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Favoriteinfo generated by hbm2java
 */
public class Favoriteinfo implements java.io.Serializable {

	private Integer favoriteId;
	private Goodsinfo goodsinfo;
	private Userinfo userinfo;
	private Date favDate;

	public Favoriteinfo() {
	}

	public Favoriteinfo(Goodsinfo goodsinfo, Userinfo userinfo) {
		this.goodsinfo = goodsinfo;
		this.userinfo = userinfo;
	}

	public Favoriteinfo(Goodsinfo goodsinfo, Userinfo userinfo, Date favDate) {
		this.goodsinfo = goodsinfo;
		this.userinfo = userinfo;
		this.favDate = favDate;
	}

	public Integer getFavoriteId() {
		return this.favoriteId;
	}

	public void setFavoriteId(Integer favoriteId) {
		this.favoriteId = favoriteId;
	}

	public Goodsinfo getGoodsinfo() {
		return this.goodsinfo;
	}

	public void setGoodsinfo(Goodsinfo goodsinfo) {
		this.goodsinfo = goodsinfo;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Date getFavDate() {
		return this.favDate;
	}

	public void setFavDate(Date favDate) {
		this.favDate = favDate;
	}

}
