package com.qx.model;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

/**
 * Level3 generated by hbm2java
 */
@JsonIgnoreProperties(value={"level2"}) 
public class Level3 implements java.io.Serializable {

	private Integer level3Id;
	private Level2 level2;
	private String level3Name;
    private String level3Img;
    
	public String getLevel3Img() {
		return level3Img;
	}

	public void setLevel3Img(String level3Img) {
		this.level3Img = level3Img;
	}

	public Level3() {
	}

	public Level3(Level2 level2, String level3Name) {
		this.level2 = level2;
		this.level3Name = level3Name;
	}

	public Integer getLevel3Id() {
		return this.level3Id;
	}

	public void setLevel3Id(Integer level3Id) {
		this.level3Id = level3Id;
	}

	public Level2 getLevel2() {
		return this.level2;
	}

	public void setLevel2(Level2 level2) {
		this.level2 = level2;
	}

	public String getLevel3Name() {
		return this.level3Name;
	}

	public void setLevel3Name(String level3Name) {
		this.level3Name = level3Name;
	}

}
