package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Level1 generated by hbm2java
 */
@JsonIgnoreProperties(value={"level2s"})  
public class Level1 implements java.io.Serializable {

	private Integer level1Id;
	private String level1Name;
	private String level1Img;
	
	public String getLevel1Img() {
		return level1Img;
	}

	public void setLevel1Img(String level1Img) {
		this.level1Img = level1Img;
	}

	@JsonIgnore
	private Set level2s = new HashSet(0);

	public Level1() {
	}

	public Level1(String level1Name, Set level2s) {
		this.level1Name = level1Name;
		this.level2s = level2s;
	}

	public Integer getLevel1Id() {
		return this.level1Id;
	}

	public void setLevel1Id(Integer level1Id) {
		this.level1Id = level1Id;
	}

	public String getLevel1Name() {
		return this.level1Name;
	}

	public void setLevel1Name(String level1Name) {
		this.level1Name = level1Name;
	}

	public Set getLevel2s() {
		return this.level2s;
	}

	public void setLevel2s(Set level2s) {
		this.level2s = level2s;
	}

}
