package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Loginfo generated by hbm2java
 */
public class Loginfo implements java.io.Serializable {

	private Integer logId;
	private Integer operaterId;
	private String operaterType;
	private String operaterIp;
	private Date logTime;
    private String operateValue;
    private Admininfo admininfo;
    private Userinfo userinfo;
    
	

	public String getOperateValue() {
		return operateValue;
	}

	public void setOperateValue(String operateValue) {
		this.operateValue = operateValue;
	}

	public Admininfo getAdmininfo() {
		return admininfo;
	}

	public void setAdmininfo(Admininfo admininfo) {
		this.admininfo = admininfo;
	}

	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	

	public Loginfo() {
	}

	public Loginfo(Integer operaterId, String operaterType, String operaterIp,
			Date logTime) {
		this.operaterId = operaterId;
		this.operaterType = operaterType;
		this.operaterIp = operaterIp;
		this.logTime = logTime;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public Integer getOperaterId() {
		return this.operaterId;
	}

	public void setOperaterId(Integer operaterId) {
		this.operaterId = operaterId;
	}

	public String getOperaterType() {
		return this.operaterType;
	}

	public void setOperaterType(String operaterType) {
		this.operaterType = operaterType;
	}

	public String getOperaterIp() {
		return this.operaterIp;
	}

	public void setOperaterIp(String operaterIp) {
		this.operaterIp = operaterIp;
	}

	public Date getLogTime() {
		return this.logTime;
	}

	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

	@Override
	public String toString() {
		return "Loginfo [logId=" + logId + ", operaterId=" + operaterId
				+ ", operaterType=" + operaterType + ", operaterIp="
				+ operaterIp + ", logTime=" + logTime + ", operateValue="
				+ operateValue + ", admininfo=" + admininfo + ", userinfo="
				+ userinfo + "]";
	}

	

}
