package com.qx.model;

// Generated 2015-9-12 22:39:10 by Hibernate Tools 3.4.0.CR1

/**
 * Orderstatus generated by hbm2java
 */
public class Orderstatus implements java.io.Serializable {

	private Integer statusid;
	private Orderinfo orderinfo;
	private Integer paystatus;
	private Integer sendstatus;

	public Orderstatus() {
	}

	public Orderstatus(Orderinfo orderinfo) {
		this.orderinfo = orderinfo;
	}

	public Orderstatus(Orderinfo orderinfo, Integer paystatus,
			Integer sendstatus) {
		this.orderinfo = orderinfo;
		this.paystatus = paystatus;
		this.sendstatus = sendstatus;
	}

	public Integer getStatusid() {
		return this.statusid;
	}

	public void setStatusid(Integer statusid) {
		this.statusid = statusid;
	}

	public Orderinfo getOrderinfo() {
		return this.orderinfo;
	}

	public void setOrderinfo(Orderinfo orderinfo) {
		this.orderinfo = orderinfo;
	}

	public Integer getPaystatus() {
		return this.paystatus;
	}

	public void setPaystatus(Integer paystatus) {
		this.paystatus = paystatus;
	}

	public Integer getSendstatus() {
		return this.sendstatus;
	}

	public void setSendstatus(Integer sendstatus) {
		this.sendstatus = sendstatus;
	}

}
