package com.qx.model;

// Generated 2015-9-12 22:39:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Orderinfo generated by hbm2java
 */
@JsonIgnoreProperties(value={"pingjiainfos","orderTime","orderstatuses","suborder"}) 
public class Orderinfo implements java.io.Serializable {

	private Integer orderId;
	private int userId;
	private Integer orderType;
	private Integer totalNum;
	private Long totalPrice;
	private String orderAddress;
	private Integer payType;
	private Date orderTime;
	private Orderstatus orderstatuses;
	private Set pingjiainfos = new HashSet(0);
	private Set<SubOrderinfo> suborder ;
	private List<SubOrderinfo> suborders ;
	private Userinfo userinfo;
	private String phone;
	
	public List<SubOrderinfo> getSuborders() {
		return suborders;
	}

	public void setSuborders(List<SubOrderinfo> suborders) {
		this.suborders = suborders;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Set getPingjiainfos() {
		return pingjiainfos;
	}

	public void setPingjiainfos(Set pingjiainfos) {
		this.pingjiainfos = pingjiainfos;
	}

	public Set getSuborder() {
		return suborder;
	}

	public void setSuborder(Set suborder) {
		this.suborder = suborder;
	}

	public Orderinfo() {
	}

	public Orderinfo(int userId) {
		this.userId = userId;
	}

	public Orderinfo(int userId, Integer orderType, Integer totalNum,
			Long totalPrice, String orderAddress, Integer payType,
			Date orderTime, Orderstatus orderstatuses) {
		this.userId = userId;
		this.orderType = orderType;
		this.totalNum = totalNum;
		this.totalPrice = totalPrice;
		this.orderAddress = orderAddress;
		this.payType = payType;
		this.orderTime = orderTime;
		this.orderstatuses = orderstatuses;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Integer getOrderType() {
		return this.orderType;
	}

	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	public Integer getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	public Long getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Long totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getOrderAddress() {
		return this.orderAddress;
	}

	public void setOrderAddress(String orderAddress) {
		this.orderAddress = orderAddress;
	}

	

	public Integer getPayType() {
		return payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Orderstatus getOrderstatuses() {
		return orderstatuses;
	}

	public void setOrderstatuses(Orderstatus orderstatuses) {
		this.orderstatuses = orderstatuses;
	}
	@Override
	public String toString() {
		return "Orderinfo [orderId=" + orderId + ", userId=" + userId
				+ ", orderType=" + orderType + ", totalNum=" + totalNum
				+ ", totalPrice=" + totalPrice + ", orderAddress="
				+ orderAddress + ", payType=" + payType + ", orderTime="
				+ orderTime + ", orderstatuses=" + orderstatuses
				+ ", suborder=" + suborder + ", suborders=" + suborders
				+ ", userinfo=" + userinfo + ", phone=" + phone + "]";
	}
//	@Override
//	public String toString() {
//		return "Orderinfo [orderId=" + orderId + ", userId=" + userId
//				+ ", orderType=" + orderType + ", totalNum=" + totalNum
//				+ ", totalPrice=" + totalPrice + ", orderAddress="
//				+ orderAddress + ", payType=" + payType + ", orderTime="
//				+ orderTime + ", orderstatuses=" + orderstatuses
//				+ ", suborders=" + suborders + ", userinfo=" + userinfo + "]";
//	}

	
	

}
