package com.qx.model;

// Generated 2015-9-6 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Userinfo generated by hbm2java
 */
@JsonIgnoreProperties(value={"favoriteinfos","pingjiainfos","pingjiainfos_1",
		"cartinfos","favoriteinfos_1","cartinfos_1","orderinfos"}) 
public class Userinfo implements java.io.Serializable {

	private Integer userId;
	private String password;
	private Integer levelStatus;
	private Date registerTime;
	private Integer vipNum;
	private Integer vipScore;
	private String userPhone;
	private String userNickName;
	private String userBuyType;
	private Set favoriteinfos = new HashSet(0);
	private Set pingjiainfos = new HashSet(0);
	private Set pingjiainfos_1 = new HashSet(0);
	private Set cartinfos = new HashSet(0);
	private Set favoriteinfos_1 = new HashSet(0);
	private Set cartinfos_1 = new HashSet(0);
	private Set orderinfos = new HashSet(0);
	
	public Userinfo(Integer userId, String userPhone, Integer sumgoods) {
		super();
		this.userId = userId;
		this.userPhone = userPhone;
		this.sumgoods = sumgoods;
	}

	private Integer sumgoods;
	
	public Integer getSumgoods() {
		return sumgoods;
	}

	public void setSumgoods(Integer sumgoods) {
		this.sumgoods = sumgoods;
	}

	public Userinfo() {
	}

	public Userinfo(String password, Integer levelStatus, Date registerTime,
			Integer vipNum, Integer vipScore, String userPhone,
			String userNickName, String userBuyType, Set favoriteinfos,
			Set pingjiainfos, Set pingjiainfos_1, Set cartinfos,
			Set favoriteinfos_1, Set cartinfos_1, Set orderinfos) {
		this.password = password;
		this.levelStatus = levelStatus;
		this.registerTime = registerTime;
		this.vipNum = vipNum;
		this.vipScore = vipScore;
		this.userPhone = userPhone;
		this.userNickName = userNickName;
		this.userBuyType = userBuyType;
		this.favoriteinfos = favoriteinfos;
		this.pingjiainfos = pingjiainfos;
		this.pingjiainfos_1 = pingjiainfos_1;
		this.cartinfos = cartinfos;
		this.favoriteinfos_1 = favoriteinfos_1;
		this.cartinfos_1 = cartinfos_1;
		this.orderinfos = orderinfos;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getLevelStatus() {
		return this.levelStatus;
	}

	public void setLevelStatus(Integer levelStatus) {
		this.levelStatus = levelStatus;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Integer getVipNum() {
		return this.vipNum;
	}

	public void setVipNum(Integer vipNum) {
		this.vipNum = vipNum;
	}

	public Integer getVipScore() {
		return this.vipScore;
	}

	public void setVipScore(Integer vipScore) {
		this.vipScore = vipScore;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserNickName() {
		return this.userNickName;
	}

	public void setUserNickName(String userNickName) {
		this.userNickName = userNickName;
	}

	public String getUserBuyType() {
		return this.userBuyType;
	}

	public void setUserBuyType(String userBuyType) {
		this.userBuyType = userBuyType;
	}

	public Set getFavoriteinfos() {
		return this.favoriteinfos;
	}

	public void setFavoriteinfos(Set favoriteinfos) {
		this.favoriteinfos = favoriteinfos;
	}

	public Set getPingjiainfos() {
		return this.pingjiainfos;
	}

	public void setPingjiainfos(Set pingjiainfos) {
		this.pingjiainfos = pingjiainfos;
	}

	public Set getPingjiainfos_1() {
		return this.pingjiainfos_1;
	}

	public void setPingjiainfos_1(Set pingjiainfos_1) {
		this.pingjiainfos_1 = pingjiainfos_1;
	}

	public Set getCartinfos() {
		return this.cartinfos;
	}

	public void setCartinfos(Set cartinfos) {
		this.cartinfos = cartinfos;
	}

	public Set getFavoriteinfos_1() {
		return this.favoriteinfos_1;
	}

	public void setFavoriteinfos_1(Set favoriteinfos_1) {
		this.favoriteinfos_1 = favoriteinfos_1;
	}

	public Set getCartinfos_1() {
		return this.cartinfos_1;
	}

	public void setCartinfos_1(Set cartinfos_1) {
		this.cartinfos_1 = cartinfos_1;
	}

	public Set getOrderinfos() {
		return this.orderinfos;
	}

	public void setOrderinfos(Set orderinfos) {
		this.orderinfos = orderinfos;
	}

	@Override
	public String toString() {
		return "Userinfo [userId=" + userId + ", password=" + password
				+ ", levelStatus=" + levelStatus + ", registerTime="
				+ registerTime + ", vipNum=" + vipNum + ", vipScore="
				+ vipScore + ", userPhone=" + userPhone + ", userNickName="
				+ userNickName + ", userBuyType=" + userBuyType + ",sumgoods = " + sumgoods + "]";
	}

}
